# Run continuous integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'maven'
    
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
        
        #run: 'mvn package'
        #shell: bash
      #- name: Build artifact
      #  run: make App.java
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: 'cyclonedx-json'
          output-file: 'sbom-cdx.json'

