# Run continuous integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'maven'
      - name: Build with Maven
        run: 'mvn package'
        shell: bash
      #- name: Build artifact
      #  run: make App.java
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: 'cyclonedx-json'
          output-file: 'sbom-cdx.json'
      - name: Attest
        uses: actions/attest-sbom@v1
        with:
          subject-path: '${{ github.workspace }}/my-app'
          sbom-path: 'sbom-cdx.json'
