# Run continuous integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'maven'
      - name: Build with Maven
        run: 'mvn package'
        shell: bash
      - name: Generate SBOM
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/sbom-cli-plugin/main/install.sh | sh -s --
          docker sbom java-example --format cyclonedx-json --output sbom.json
      - name: Upload SBOM to Dependency-Track
        run: |
          curl -X "POST" http://antovski.ddns.net:8091/api/v1/bom -H 'Content-Type: multipart/form-data' -H "X-Api-Key: odt_2uaVxom3Gy6S0easrcPxTu8YnEjGuc6S" -F "autoCreate=true" -F "projectName=java-example" -F "projectVersion=1.0" -F "bom=@sbom.json"
    