# Run continuous integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'maven'
      - name: Build with Maven
        run: 'mvn package cyclonedx:makeAggregateBom'
        shell: bash
      #- name: Upload SBOM to DT
      #  run: curl -X "POST" http://antovski.ddns.net:8091/api/v1/bom -H 'Content-Type:multipart/form-data' -H 'X-Api-Key:odt_jwqMzLAEplZlA0WHat9lps0UC40p99qb' -F 'project=ff03814a-d833-47a3-bd73-7536e4b56d7e' -F 'bom=@bom.json'

      - name: Experiment -> install cdxgen
        run: 'npm install -g @cyclonedx/cdxgen'
      - name: Experiment -> generate bom
        run: cdxgen -o cdxbom.json
      - name: Experiment -> Upload SBOM to DT
        run: curl -X "POST" http://antovski.ddns.net:8091/api/v1/bom -H 'Content-Type:multipart/form-data' -H 'X-Api-Key:odt_jwqMzLAEplZlA0WHat9lps0UC40p99qb' -F 'project=ff03814a-d833-47a3-bd73-7536e4b56d7e' -F 'bom=@bom.json'


      #- name: Upload SBOM to DT
      #  uses: DependencyTrack/gh-upload-sbom@v3
      #    with:
      #    serverHostname: 'http://antovski.ddns.net:8091/api/v1/bom/'
      #    apiKey: 'odt_jwqMzLAEplZlA0WHat9lps0UC40p99qb'
      #    project: '30309883-16cc-4813-9dc7-1df8db4a3444'
      #    projectVersion: 'master'
      #    bomFilename: "./sbom/bom.xml"
